name: Lint and Format

on:
  pull_request:
    branches:
      - main

jobs:
  check-license:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Ruff and dependencies
        run: |
          pip install -r requirements.txt
          pip install ruff

      - run: ruff check . --output-format=github
      - run: ruff format . --check