name: Unit Test

on:
  pull_request:
    branches:
      - main

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      subdirs: ${{ steps.set-subdir.outputs.target-list }}
    steps:
      - uses: actions/checkout@v3
      - name: Get src subdirectories
        id: set-subdir
        run: |
          list=`find ./src -name requirements.txt | sed -r "s/^.*src\/(.*)\/requirements.txt/\1/g" | jq -R -s -c 'split("\n")[:-1]' | jq -c .`
          echo "target-list=$list" >> $GITHUB_OUTPUT
  unittest:
    runs-on: ubuntu-latest
    needs: set-matrix
    strategy:
      matrix:
        target: ${{ fromJson(needs.set-matrix.outputs.subdirs) }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        working-directory: ./src/${{ matrix.target }}
        run: pip install -r requirements.txt

      - name: unittest
        working-directory: ./src/${{ matrix.target }}
        run: python -m unittest discover -s ./test  -p 'test_*.py'